env:
  DOCKER_COMPOSE_VERSION: 1.12.5

sudo: required

services:
  - docker

before_install:
  - chmod u+x bin/rails
  - docker-compose --version
  - docker-compose build
  - sudo docker-compose up -d
  - docker ps
  - docker-compose run -e "RAILS_ENV=test" web rake db:create db:migrate

script:
  - docker-compose run -e "RAILS_ENV=test" app rake test
