env:
  DOCKER_COMPOSE_VERSION: 1.12.5

sudo: required

before_install:
  - docker-compose -v
  - docker-compose build
  - docker ps
  - psql -c 'create database testpg' -U postgres
  - docker-compose run web bundle exec rake db:test:prepare
  - bundle exec rspec spec/
