env:
  DOCKER_COMPOSE_VERSION: 1.12.5

sudo: required

services:
  - docker

before_install:
  - chmod u+x bin/rails
  - docker-compose --version

before_script:
  - docker-compose build
  - sudo docker-compose up -d
  - docker ps
  - docker inspect marstracker_db_1
  - psql -c 'create database marstracker_test;' -U postgres
  - docker-compose run web rake db:migrate RAILS_ENV=test
  - psql -c 'create database marstracker_test;' -U postgres

script:
  - docker-compose run -e "RAILS_ENV=test" web bundle exec rspec
