env:
  DOCKER_COMPOSE_VERSION: 1.12.5

sudo: required

services:
  - docker

before_install:
  - chmod u+x bin/rails
  - docker-compose --version
  - docker-compose build
  - sudo docker-compose up -d
  - docker ps
  - docker inspect marstracker_db_1
  - psql -c 'create database marstracker_test;' -U postgres
  - docker-compose run db rake db:migrate

script:
  - docker-compose run -e "RAILS_ENV=test" bundle exec rspec
