env:
  DOCKER_COMPOSE_VERSION: 1.12.5

sudo: required

services:
  - docker

before_install:
  - chmod u+x bin/rails
  - docker-compose --version
  - docker-compose build
  - sudo docker-compose up -d
  - docker ps
  - docker inspect marstracker_db_1
  - sudo service postgresql restart
  - psql -c 'create database marstracker_test;' -U postgres
  - docker-compose run web bundle exec rake db:create:all
  - docker-compose run web bundle exec rake db:migrate RAILS_ENV=test
  - docker-compose run -e "RAILS_ENV=test" web bundle exec rspec

bundler_args: --binstubs=./bundler_stubs