env:
  DOCKER_COMPOSE_VERSION: 1.12.5

sudo: required

services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose build
  - sudo docker-compose up
  - sudo docker ps
  - psql -c 'create database marstracker_test' -U postgres
  - sudo docker-compose run web bundle exec rake db:test:prepare
  - bundle exec rspec spec/
