# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development: &default
  adapter: postgresql
  database: marstracker_development
  min_messages: WARNING
  pool: 5
  username: postgres
  password: <%= Rails.application.secrets[:database][:password] %>
  host: db

test:
  <<: *default
  database: marstracker_test

production:
  <<: *default
  databse: marstracker_production